# pyproject.toml

[build-system]
requires = ["hatchling", "hatch-vcs", "pybind11"]
build-backend = "hatchling.build"

[project]
name = "cooppush"
dynamic = ["version"] # Version will be taken from git tags
authors = [
  { name="Timothy Flavin", email="timothy.c.flavin@gmail.com" },
]
description = "MPE inspired push environment with tunable inter-action dependence for coop MARL"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
[project.urls]
"Homepage" = "https://github.com/Timothy-Flavin/CoopPush/"
"Bug Tracker" = "https://github.com/Timothy-Flavin/CoopPush/issues"

[tool.hatch.version]
source = "vcs" # Use hatch-vcs to get version from git tags

[tool.hatch.build.targets.wheel]
# This is the key section that replaces setup.py
# It tells hatchling to include the compiled C++ module in the wheel
#packages = ["cooppush"]
packages = ["src/cooppush"]
force_include = {
    "src/cooppush/*.so" = "cooppush",  # For Linux and macOS
    "src/cooppush/*.pyd" = "cooppush"  # For Windows
}
[tool.hatch.build.hooks.custom]
# This defines a custom build script to run before building the wheel
path = "hatch_build.py"

[tool.cibuildwheel]
# This tells cibuildwheel to build for all supported Python versions on all platforms.
# The '*' is a wildcard that matches all versions it finds.
build = "cp3*-*"
skip = ""

[tool.cibuildwheel.windows]
# Explicitly tell cibuildwheel to build for all supported CPython 3 versions on Windows.
# The '*' is a wildcard.
build = "cp3*-win_amd64"
