# .github/workflows/publish.yml

name: Build and publish to PyPI

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v0.1.0

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # No python-version matrix needed here!
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        # No 'with' block or extra config needed for simple cases
        uses: pypa/cibuildwheel@v2.12.0

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl

  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4 # <-- FIX HERE
        with:
          name: artifact
          path: dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}