name: Build and Publish to PyPI

on:
  workflow_dispatch: # Allows you to trigger the run manually from the Actions tab
  push:
    tags:
      - 'v*'

jobs:
  build_and_publish:
    name: Build and publish on ${{ matrix.os }}
    # 'runs-on' and 'strategy' must be at the same indentation level
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    permissions:
      id-token: write # Required for trusted publishing

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build sdist (source distribution)
      run: python -m build --sdist

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.19.1
      env:
        # Tell cibuildwheel to put all built wheels in the 'dist' folder
        CIBW_OUTPUT_DIR: dist

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.9.0